// Code generated by go2go; DO NOT EDIT.


//line reverse.go2:7
package goreverse

//line reverse.go2:7
import "testing"

//line reverse.go2:14
func ReverseWithInterval(b []byte, left, right int) string {
	for left < right {
		b[left], b[right] = b[right], b[left]
		left++
		right--
	}
	return string(b)
}

//line reverse.go2:24
func Reverse(res []int) []int {
	for i := 0; i < len(res)/2; i++ {
		res[i], res[len(res)-i-1] = res[len(res)-i-1], res[i]
	}
	return res
}

//line reverse.go2:29
type Importable୦ int

//line reverse.go2:29
var _ = testing.AllocsPerRun
